name: petsird
channels:
  - conda-forge
  - defaults
dependencies:
  - bash-completion>=2.11
  - cmake>=3.21.3
  - fmt>=8.1.1
  - cxx-compiler
  - hdf5>=1.12.1
  - howardhinnant_date>=3.0.1
  - just=1.36.0
  - ninja>=1.11.0
  - nlohmann_json>=3.11.2
  - shellcheck>=0.8.0
  - xtensor>=0.24.2, <0.26.0
  - xtensor-blas
